import { ComponentFactoryResolver, Injectable } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { Message } from '../message.model';
import { catchError, map, Subject, throwError } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class MessageService {
  messageFetched: Subject<any> = new Subject();
  errorsubject: Subject<any> = new Subject();
  constructor(
    private readonly httpClient: HttpClient,
    private componentFactoryResolver: ComponentFactoryResolver
  ) {}

  fetchMessages() {
    return this.httpClient.get<{ [key: string]: Message }>(
      'https://angular-backend-3d5f9-default-rtdb.firebaseio.com/messages.json',
      {
        headers: new HttpHeaders({
          customerHeader: 'HEADERS',
        }),
        params: new HttpParams().set('print', 'preety'),
      }
    );
    // .pipe(
    //   map((rowData) => {
    //     const messageArray: Message[] = [];
    //     for (const key in rowData) {
    //       if (rowData.hasOwnProperty(key)) {
    //         messageArray.push({
    //           title: rowData[key].title,
    //           content: rowData[key].content,
    //           id: key,
    //         });
    //       }
    //     }
    //     return messageArray;
    //   })
    // )
    // .subscribe((res) => {
    //   console.log('Fetched messages:', res);
    //   this.messageFetched.next(res);
    // });
  }

  createMessage(messageData: { title: string; content: string }) {
    this.httpClient
      .post(
        'https://angular-backend-3d5f9-default-rtdb.firebaseio.com/messages.json',
        messageData,
        {
          params: new HttpParams().set('print', 'preety'),
          headers: new HttpHeaders({
            customerHeader: 'HEADERS',
          }),
        }
      )
      .subscribe(
        (res) => {
          console.log('responce generated by Post Method', res);
        },
        (error) => {
          this.errorsubject.next(error);
        }
      );
  }

  deleteMessage() {
    return this.httpClient.delete(
      'https://angular-backend-3d5f9-default-rtdb.firebaseio.com/messages.json',
      {
        params: new HttpParams().set('print', 'preety'),
        headers: new HttpHeaders({
          customerHeader: 'HEADERS',
        }),
      }
    );
  }
}
